name = "MulticomplexNumbers"
uuid = "d39bb3b7-cc9c-4bb9-be86-52b494dfee17"
version = "0.1.0"
authors = ["Chris Waudby <c.waudby@ucl.ac.uk> and contributors"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[extensions]
FFTWExt = "FFTW"

[compat]
FFTW = "1.7"
LinearAlgebra = "1.10"
PrecompileTools = "1.1"
StaticArrays = "1.9"
julia = "1.10"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets", "FFTW"]
